# -*- coding: utf-8 -*-
"""Projet individuel la chlordécone aux Antilles françaises .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFnIbn_sKF93-wa8-O6_NSxoQuLHtnmh

## Introduction sur les données de chloredéconne

La chlordécone est un pesticide organochloré utilisé aux Antilles françaises jusqu’au début des années 1990. Sa persistance dans les sols, les eaux et les chaînes alimentaires en fait aujourd’hui un enjeu sanitaire, environnemental et socio-économique majeur.
l'ojectif de ce projet est de nettoyer et transformer les données, mener des analyses statistiques et exploratoires avancées.

## Importation des librairies
"""

import plotnine as pp
import numpy as np
import pandas as pd
from google.colab import files
import io
import re
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.impute import KNNImputer
import scipy.stats as stats
from scipy.spatial.distance import pdist
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import folium
import geopandas as gpd

"""##I-Importations et préparation des données"""

uploaded=files.upload()

don= pd.read_csv("BaseCLD2026.csv",sep=";", header=0)
don=pd.DataFrame(don)
print(don.head())
don.shape

don.dtypes

"""Vérification si les indicateurs  contiennent les données manquantes"""

don.isna().sum()

# Carte de chaleur des valeurs manquantes
plt.figure(figsize=(14,8))
sns.heatmap(don.isna(), cmap="viridis", yticklabels=False) # les Zones en jaunes sont les valeurs manquantes
plt.title(" Valeurs manquantes dans chlordécone")
plt.show()
# Les Variables qui contienneent les données manquantes sont : Type_sol,commu_lab,.......

"""Dans la suite de continuer l'analyse, on va retirer la variable histoBanane_Histo_ban, car elle contient plusieurs données manquantes.

Vérification des types de variables et transformation des formats de ses variables.
"""

# --- 1. FORMAT NUMÉRIQUE (Nombres décimaux) ---
# Transforme le texte avec virgule en nombre compréhensible par Python
cols_float = [
    'Taux_Chlordecone', 'Taux_5b_hydro', 'X', 'Y',
    'mnt_tpi_mean', 'mnt_tri_mean', 'mnt_rugosite_mean', 'mnt_pente_mean'
]
for col in cols_float:
    if col in don.columns:
        don[col] = pd.to_numeric(don[col].astype(str).str.replace(',', '.'), errors='coerce')

# --- 2. FORMAT DATE ---
cols_date = ['Date_prelevement', 'Date_enregistrement', 'Date_analyse']
for col in cols_date:
    if col in don.columns:
        don[col] = pd.to_datetime(don[col], dayfirst=True, errors='coerce')

# --- 3. FORMAT ENTIER (Année et ID) ---
# On utilise Int64 (avec majuscule) qui permet de garder les NaN tout en étant un entier
cols_int = ['ID', 'ANNEE']
for col in cols_int:
    if col in don.columns:
        don[col] = pd.to_numeric(don[col], errors='coerce').astype('Int64')

# --- 4. FORMAT TEXTE (Catégories) ---
cols_str = ['COMMU_LAB', 'Sol_simple', 'type_sol', 'Operateur_chld', 'Operateur_5b', 'RAIN']
for col in cols_str:
    if col in don.columns:
        don[col] = don[col].astype(str)
print(don.dtypes)

don.head()

""" Vérification et suppression des doublons"""

print(don.duplicated().sum())
# suppression des doublons dans sur les données chlordéconnes
don = don.drop_duplicates()

"""La colonne des communes contient des formats inversés type "ROBERT (LE)". Nous utilisons la librairie re pour repérer ce motif et le remettre dans le bon ordre ("LE ROBERT")."""

def COMMU_LAB_TRANSFORM(name):
    """Transforme 'MOT(LE)' ou 'MOT (LA)' en 'LE MOT'."""
    if pd.isna(name):
        return name
    name_str = str(name).strip().upper()
    # Recherche du motif : un mot suivi de (LE/LA/LES)
    match = re.match(r"^(.*?)\s*\((LE|LA|LES|L\')\)$", name_str)
    if match:
        # On place l'article devant le nom
        return f"{match.group(2)} {match.group(1)}".strip()
    return name_str

# On applique la transformation directement sur la colonne existante
if 'COMMU_LAB' in don.columns:
    don['COMMU_LAB'] = don['COMMU_LAB'].apply(COMMU_LAB_TRANSFORM)

    print("✅ Colonne 'COMMU_LAB' mise à jour avec succès.")
    # On affiche les valeurs uniques pour vérifier le résultat
    print(don['COMMU_LAB'].unique()[:10])

"""
## II-Gestion des variables contenant des valeurs manquantes."""

#2.calcul du nombre de valeurs manquantes par colonne
missing_values = don.isnull().sum()
print("Nombre de valeurs manquantes par colonne:", missing_values)

"""Pour les variables dont la proportion des valeurs manquantes sont petits, je propose d'utiliser la méthode de KNN pour remplacer ses valeurs vides, en utilisant les coordonnées goéographiques.

L'analyse de la variable histoBanane_Histo_ban révèle plusieurs données sont manquantes (NaN). Dans le contexte de la pollution à la chlordécone en Martinique, cette absence d'information n'est pas aléatoire :

Hypothèse métier : La chlordécone était spécifiquement utilisée pour traiter le charançon du bananier. Une absence d'enregistrement dans l'historique "banane" indique très probablement que la parcelle n'a jamais accueilli cette culture.

Action corrective : Nous avons procédé à une imputation par la valeur 0.

Objectif : Transformer les valeurs manquantes en une information exploitable ("Absence de culture de banane") afin de conserver l'intégralité du jeu de données et de permettre au modèle statistique de comparer les zones à risque des zones présumées saines.
"""

#1 Imputation de histoBanane_Histo_ban par 0
don['histoBanane_Histo_ban'] = don['histoBanane_Histo_ban'].fillna(0)

"""Pour la variable type_sol, les données manquantes la composant sont un peu plus nombreux, pour éviter de perdre les informations, j'utilise la méthode de la mode pour remplacer ses valeurs manquantes."""

#2. Imputation de type_sol par le mode
mode_type_sol = don['type_sol'].mode()[0]
don['type_sol'] = don['type_sol'].fillna(mode_type_sol)
don['COMMU_LAB']=don['COMMU_LAB'].fillna(mode_type_sol)

"""Suppression des lignes restantes avec des NA pour les colonnes dont elle contiennent peu de valeurs manquantes, car elle n'aura aucun impact sur l'analyse des données."""

# 1. On remplace les chaînes de caractères "nan", "NaN", " " par de vrais objets NaN
don = don.replace(['nan', 'NaN '], np.nan)
don = don.dropna()
don

"""Détection des Valeurs Aberrantes
Nous utilisons la méthode de la boîte à moustache  pour identifier les valeurs aberrantes (outliers) sur le taux de chlordécone et sur le taux mesuré de 5b-hydro chlordecone.
"""

# 2. Box plot seul (format horizontal, adapté pour voir les valeurs extrêmes)
plt.figure(figsize=(10, 3))
sns.boxplot(x=don['Taux_Chlordecone'], color='Orange')
plt.title('Box plot du Taux de Chlordécone')
plt.xlabel('Taux de Chlordécone')
plt.show()

# 2. Box plot vertical
plt.figure(figsize=(4, 6)) # On ajuste la taille (plus haut que large)
sns.boxplot(y=don['Taux_5b_hydro'], color='skyblue')
plt.title('Box plot du Taux de Taux_5b_hydro')
plt.ylabel('Taux de Chlordécone') # On change xlabel en ylabel
plt.show()

don.shape

"""## III-Analyse statistique descriptives

Le Nombre de prélèvements par type de sol
"""

(
    pp.ggplot(don, pp.aes(x="Sol_simple"))
    + pp.geom_bar(fill="red")
    + pp.geom_text(
        pp.aes(label=pp.after_stat('count')),
        stat="count",
        va="bottom",
        nudge_y=0.5  # Ajuste cette valeur selon l'échelle de tes données
    )
    + pp.labs(
        title="Nombre de prélèvements par type de sol",
        x="Type de sol",
        y="Nombre de prélèvements"
    )
)

"""Analyse univariée du nombre de parcelle par commune : la Commune de la Morne-Rouge contient la plus forte effecttif de parcelles
prélévées.(Le nombre de prmèvement par type de commune)
"""

(
    pp.ggplot(don, pp.aes(x="COMMU_LAB")) +
    pp.geom_bar(fill="skyblue") +
    pp.labs(
        title="Répartition par commune",
        x="Nom de la commune",
        y=" Nombre de prélèvements"
    ) +
    pp.theme(axis_text_x=pp.element_text(angle=45, hjust=1))
)

"""Dans le but d'analyser uniquement les données Martiniques, on supprimera les données hors-martinique"""

# On redéfinit 'don' en filtrant les lignes
don = don[don['COMMU_LAB'] != 'HORS MARTINIQUE']

(
    pp.ggplot(don, pp.aes(x="COMMU_LAB", fill="COMMU_LAB"))
    + pp.geom_bar(show_legend=False) # Supprime la légende qui déforme le graphique
    + pp.coord_flip()
    + pp.labs(
        title="Nombre de prélèvements par commune",
        x="Commune",
        y="Nombre de prélèvements"
    )
    + pp.theme(
        axis_text_x=pp.element_text(angle=0, hjust=0.5), # Remis à 0 car avec coord_flip c'est plus lisible horizontalement
        figure_size=(8, 10) # Tu peux ajuster la taille ici si la liste des communes est longue
    )
)

don.shape

"""## IV- Algorithme des Centres Mobiles (K-Means)
Avec le K-Means nous partitionnons les données en minimisant l'inertie intra-classe. Nous allons fixer `k=3` pour identifier 3 profils de contamination (Faible, Moyen, Élevé).

Grahique du coude
"""

# 2. Sélection des variables quantitatives (identique à l'ACP)
colonnes_num = don.select_dtypes(include=['float64', 'int64']).columns
colonnes_a_garder = [col for col in colonnes_num if col not in ['ID', 'ANNEE']]
don_num = don[colonnes_a_garder].copy()

# Explicitly handle infinite values before scaling
don_num = don_num.replace([np.inf, -np.inf], np.nan)
don_num = don_num.dropna()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(don_num)

# 4. Calcul de l'inertie pour K allant de 1 à 10
inerties = []
K_range = range(1, 11)

for k in K_range:
    # n_init=10 est une bonne pratique pour éviter de tomber dans un minimum local
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inerties.append(kmeans.inertia_)

print("Inerties pour K de 1 à 10 :", inerties)

# 5. Création du graphique du Coude
plt.figure(figsize=(8, 5))
plt.plot(K_range, inerties, marker='o', color='green', linestyle='-')
plt.title('Méthode du Coude pour déterminer le nombre  de clusters')
plt.xlabel('Nombre de clusters (K)')
plt.ylabel('Inertie intra-classe')
plt.xticks(K_range)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

#1. Initialisation et entrainement du modèle k-means final avec k = 4

kmeans_final = KMeans(n_clusters=4, random_state=42, n_init=10)
clusters = kmeans_final.fit_predict(X_scaled)

print("Centres des clusters (en données standardisées) :\n", kmeans_final.cluster_centers_)
print("Labels des clusters pour chaque échantillon :\n", clusters)

#2 ajout de la colonne 'Cluster' a nootre jeu de donnée proprée
don_num['cluster'] = clusters

# Align cluster labels with the original 'don' DataFrame
# Create a new series with the same index as 'don' and fill matching indices
clusters_aligned_with_don = pd.Series(np.nan, index=don.index)
clusters_aligned_with_don.loc[don_num.index] = don_num['cluster']
don['Cluster_KMeans'] = clusters_aligned_with_don

print("Distribution des échantillons par cluster :\n", don_num['cluster'].value_counts())
print("Moyennes des variables par cluster :\n", don_num.groupby('cluster').mean())

"""## V-Classification Ascendante Hiérarchique (CAH) & Distance de manathan

Nous allons implémenter une CAH. Au lieu d'utiliser la distance euclidienne classique, nous utilisons la **distance de manathan**, particulièrement adaptée aux données écologiques et d'abondance (comme la concentration de molécules)
"""

# Pour éviter de faire exploser la mémoire avec la CAH, on prend un échantillon représentatif
# (La CAH est très gourmande en mémoire sur 30 000 lignes)
df_sample = df_model.sample(n=1000, random_state=42)

# Ensure the selected columns for clustering are clean of infinite values and NaNs
# This creates a cleaned subset that will be scaled
X_for_scaling = df_sample[cols_clustering].replace([np.inf, -np.inf], np.nan).dropna()

# Create and fit a new scaler specifically for the CAH features
# This ensures the scaler is only aware of 'Taux_Chlordecone' and 'Taux_5b_hydro'
cah_scaler = StandardScaler()
X_sample = cah_scaler.fit_transform(X_for_scaling)

# Calcul de la matrice de dissimilarité avec la distance de Manhattan
# Ensure all values are positive for pdist with 'cityblock' if any negative values exist after scaling
X_positive = X_sample - X_sample.min() + 0.01
dist_matrix = pdist(X_positive, metric='cityblock')

# Génération de l'arbre hiérarchique (méthode de Ward)
Z = linkage(dist_matrix, method='average')

# Affichage du Dendrogramme
plt.figure(figsize=(10, 6))
dendrogram(Z, truncate_mode='lastp', p=30, leaf_rotation=90., leaf_font_size=10., show_contracted=True)
plt.title('Dendrogramme CAH (Distance de Manhattan)')
plt.xlabel('Index des parcelles (ou taille des nœuds)')
plt.ylabel('Distance de Manhattan')
plt.axhline(y=1.5, color='r', linestyle='--') # Ligne de coupe suggérée
plt.show()

# Découpage de l'arbre en 3 clusters pour comparer avec le K-Means
# Assign cluster labels back to the original df_sample based on the cleaned sample's indices
cluster_labels_cah = fcluster(Z, 3, criterion='maxclust')
df_sample.loc[X_for_scaling.index, 'Cluster_CAH'] = cluster_labels_cah

"""## VI-ACP (Analyse en Composantes Principales)"""

# 1. Sélection et préparation des variables pour l'ACP
features = ['Taux_Chlordecone', 'Taux_5b_hydro', 'mnt_pente_mean',
            'mnt_tpi_mean', 'mnt_rugosite_mean']

# Handle the 'RAIN' column: convert ranges to numerical midpoints
def convert_rain_to_midpoint(rain_str):
    if isinstance(rain_str, str) and '-' in rain_str:
        try:
            parts = rain_str.split('-')
            lower = float(parts[0])
            upper = float(parts[1])
            return (lower + upper) / 2
        except ValueError:
            return np.nan
    return np.nan # Return NaN for non-string or unparseable values

don['RAIN_midpoint'] = don['RAIN'].apply(convert_rain_to_midpoint)
features.append('RAIN_midpoint')

# Create the feature matrix and drop any rows with NaN values resulting from the conversion
data_pca = don[features]

# Explicitly handle infinite values before scaling
data_pca = data_pca.replace([np.inf, -np.inf], np.nan)
data_pca = data_pca.dropna()

# 2. Standardisation
scaler = StandardScaler()
X_scaled = scaler.fit_transform(data_pca)

# 3. Application de l'ACP
pca = PCA()
pca.fit(X_scaled)

# Get the projected data
pca_proj = pca.transform(X_scaled)

# 4. Affichage de la variance expliquée
plt.figure(figsize=(10, 6))
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('Nombre de composantes principales')
plt.ylabel('Variance expliquée cumulative')
plt.title('Variance expliquée par les composantes principales')
plt.grid(True)
plt.show()

# 5. Affichage des valeurs propres
print("Valeurs propres :", pca.explained_variance_)

# 6. Affichage des contributions des variables aux premières composantes
# Créer un DataFrame pour les contributions
components_df = pd.DataFrame(pca.components_, columns=data_pca.columns)

plt.figure(figsize=(12, 8))
sns.heatmap(components_df.head(5), cmap='viridis', annot=True, fmt=".2f")
plt.title('Contributions des variables aux 5 premières composantes principales')
plt.show()

# Création d'un DataFrame pour la visualisation
df_pca = pd.DataFrame(pca_proj[:, :2], columns=['PC1', 'PC2'])

plt.figure(figsize=(10, 7))
sns.scatterplot(data=df_pca, x='PC1', y='PC2', alpha=0.6)
plt.title("Projection des parcelles sur les deux premiers axes de l'ACP")
plt.axhline(0, color='green', lw=1)
plt.axvline(0, color='grey', lw=1)
plt.show()

#1. Calcul des coordonnées des variables (corrélations avec les axes F1 et F2 )
#Formule :  vecteur_propre * racine(valeur_propre)

racine_valeurs_propres = np.sqrt(pca.explained_variance_)
correlations = pca.components_ * racine_valeurs_propres[:, np.newaxis]

print("Corrélations des variables avec les axes F1 et F2 :\n", correlations[:2])

# 2. Création de la figure
fig, ax = plt.subplots(figsize=(9, 9))

# 3. Tracé du cercle unitaire
cercle = plt.Circle((0,0), 1, color='blue', fill=False, linestyle='--')
ax.add_artist(cercle)

# 4. Affichage des flèches pour chaque variable
for i, nom_variable in enumerate(features): # Changed colonnes_a_garder to features
    ax.arrow(0, 0, correlations[0, i], correlations[1, i],
             head_width=0.03, head_length=0.04, fc='yellow', ec='yellow', alpha=0.8)

    # Placement des étiquettes (noms des variables) légèrement décalées de la flèche
    ax.text(correlations[0, i] * 1.15, correlations[1, i] * 1.15,
            nom_variable, color='black', ha='center', va='center', fontsize=10)

# 5. Esthétique du graphique (lignes 0, limites, titres)
plt.axhline(0, color='gray', linestyle='--', linewidth=1)
plt.axvline(0, color='gray', linestyle='--', linewidth=1)
plt.xlim(-1.2, 1.2)
plt.ylim(-1.2, 1.2)

# Titre avec la variance expliquée par les axes 1 et 2
var_f1 = pca.explained_variance_ratio_[0] * 100
# Titre avec la variance expliquée par les axes 1 et 2
var_f1 = pca.explained_variance_ratio_[0] * 100
var_f2 = pca.explained_variance_ratio_[1] * 100
plt.title("Cercle des corrélations (Axes F1 et F2)", fontsize=16)
plt.xlabel(f"F1 ({var_f1:.1f}%)")
plt.ylabel(f"F2 ({var_f2:.1f}%)")
plt.grid(True, linestyle=':', alpha=0.6)

plt.show()

"""## VII-Cartographie
Objectif : Visualiser géographiquement le taux de chlordécone pour aider les pouvoirs publics à cibler les zones d'interdiction ou de prévention.
"""

import folium
import geopandas as gpd

# 1. Préparation des données (on s'assure d'avoir les clusters et les coordonnées)
df_map = don.dropna(subset=['X', 'Y']).copy()
# Drop rows where 'Cluster_KMeans' is NaN to avoid the ValueError
df_map = df_map.dropna(subset=['Cluster_KMeans']).copy()

# 2. Transformation en coordonnées GPS (WGS84) via GeoPandas
gdf = gpd.GeoDataFrame(
    df_map,
    geometry=gpd.points_from_xy(df_map['X'], df_map['Y']),
    crs="EPSG:5490" # Système local (UTM 20N)
)
gdf = gdf.to_crs("EPSG:4326") # Conversion en Lat/Lon pour Folium

df_map['Lat_GPS'] = gdf.geometry.y
df_map['Lon_GPS'] = gdf.geometry.x

# 3. Création de la carte centrée sur tes données
# On prend la moyenne des Lat et Lon pour centrer automatiquement
centre_carte = [df_map['Lat_GPS'].mean(), df_map['Lon_GPS'].mean()]
ma_carte = folium.Map(location=centre_carte, zoom_start=11, tiles='CartoDB positron')

# 4. Définition des couleurs selon tes profils de risque
couleurs_cluster = {
    0: 'green',   # Zone saine
    1: 'orange',  # Zone intermédiaire / pentue
    2: 'red',     # Zone critique
    3: 'black'    # Anomalies (si k=4)
}

# 5. Ajout des points sur la carte
for _, row in df_map.iterrows():
    cluster_id = int(row['Cluster_KMeans']) # On s'assure que c'est un entier

    # Choix de la couleur
    couleur = couleurs_cluster.get(cluster_id, 'gray')

    folium.CircleMarker(
        location=[row['Lat_GPS'], row['Lon_GPS']],
        radius=5,
        # Popup enrichi pour l'analyse
        popup=(f"<b>Cluster :</b> {cluster_id}<br>"
               f"<b>Chlordécone :</b> {row['Taux_Chlordecone']:.2f} µg/kg<br>"
               f"<b>5b-hydro :</b> {row['Taux_5b_hydro']:.2f}"),
        color=couleur,
        fill=True,
        fill_color=couleur,
        fill_opacity=0.7,
        weight=1
    ).add_to(ma_carte)

# Affichage de la carte
ma_carte

"""La carte des Antilles répartit les zones selon quatre profils : le Vert pour les zones saines, l'Orange pour les zones sous surveillance, le Rouge pour les zones en danger, et le Noir pour les anomalies.

## Conclusion
L’analyse multidimensionnelle de la contamination au chlordécone a permis de transformer des données brutes en une véritable stratégie de lecture du risque environnemental. L'application de l'algorithme des K-Means a révélé une structuration nette du territoire, classant les parcelles selon leur niveau de vulnérabilité.

La cartographie interactive constitue l'aboutissement de ce travail, offrant une visualisation spatiale immédiate des zones de vigilance. Le code couleur retenu permet d'identifier précisément les secteurs : le vert pour les zones saines, l'orange pour les zones sous surveillance, le rouge pour les zones en danger et le noir pour les anomalies de mesure.

La cohérence entre les résultats statistiques et la réalité géographique confirme la fiabilité du modèle. Ces résultats constituent un véritable outil d'aide à la décision pour orienter les politiques de surveillance sanitaire et la gestion des sols aux Antilles.
"""